server:
  port: 8086

spring:
  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always

jpa:
  database: h2
  hibernate:
      dialect: org.hibernate.dialect.H2Dialect
  ddl-auto: create #automatic schema creation (enabled)

#logging:
#  level:
#    org:
#      springframework: ALL
